---
langs: [fr_FR]
baseurl: "/"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
- vendor
title: "Documentation Jeedom"
description: "Ceci est la documentation, lier à la solution domotique Jeedom."
author: "Ynats"
social:
  name: Jeedom
  links:
    - https://github.com/Ynats/jeedom-previsy
community: https://community.jeedom.com
market: https://market.jeedom.com
blog: https://blog.jeedom.com
doc: https://doc.jeedom.com
theme: jekyll-theme-cayman